[ids]
*

[main]
capslock = overload(nav, esc)

[nav]
h = left
j = down
k = up
l = right

# u = pageup
# d = pagedown
y = home
o = end

u = pageup
d = pagedown
a = home
e = end

b = C-left
f = C-right

w = C-backspace
